# Generated by Django 2.0.5 on 2018-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
